---
language: c
os: linux
git:
  depth: 1
# branches:
#   only:
#       - /.*/
notifications:
  email:
    recipients:
      - housni.yakoob@gmail.com
    on_success: never
    on_failure: change
# install:
  # TODO: Install https://github.com/replicatedhq/dockerfilelint
before_script:
  - shellcheck {core,response,storage,test,tests,util}/*.sh meemaw.sh
  # - git clone --depth 1 https://github.com/replicatedhq/dockerfilelint.git ./dockerfilelint
  # - ./dockerfilelint/bin/dockerfilelint ./Dockerfile
script:
  - ./test/test.sh
  # TODO: generate docs: https://github.com/zdharma/zshelldoc