---
language: c
os: linux
git:
  depth: 1
sudo: required
services:
  - docker
# branches:
#   only:
#       - /.*/
notifications:
  email:
    recipients:
      - housni.yakoob@gmail.com
    on_success: never
    on_failure: change
before_install:
  - make prepare
script:
  - make lint
  - make test
  # - make gen-docs