name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Info
      run: make stats

    - name: Install dependencies
      run: make prepare

    - name: Lint test
      run: make check.lint

    - name: General tests
      run: make check.test
